
spring:
  application:
    name: "@project.name@"
  jackson:
    serialisation:
      indent_output: true   # Pretty-print JSON responses

info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"

server:
  port: 5000

management:
  endpoints:
    web:
      exposure:
        include: "*"    # Enable additional actuator endpoints

logging:
  level:
    ROOT: INFO
    com.zeroout.spring.cloud.pricing.resource: TRACE
